clinics = {
'Abducens nerve palsy (VIth cranial nerve)':'Neurology',
'Acetaminophen poisoning':'Emergency Medicine',
'Achalasia':'Gastroenterology',
'Acne':'Dermatology',
'Acquired Immunodeficiency syndrome (AIDS)':'Infectious',
'Acromegaly':'Endocrinology',
'Acute HIV infection (acute retroviral syndrome, early symptomatic HIV Infection)':'Infectious',
'Acute anticholinergic syndrome':'Emergency Medicine',
'Acute bronchitis':'Pulmonary ',
'Acute cholinergic syndrome':'Emergency Medicine',
'Acute hypnotic toxicity':'Emergency Medicine',
'Acute interstitial nephritis':'Nephrology',
'Acute intestinal ischemia':'General Surgery Division',
'Acute liver failure':'Gastroenterology',
'Acute lymphoblastic leukemia (ALL)':'Oncology',
'Acute myeloid leukemia (AML)':'Oncology',
'Acute mastoiditis':'Ear, Nose, Throat, Head and Neck Surgery Department',
'Acute pharyngitis':'Ear, Nose, Throat, Head and Neck Surgery Department',
'Acute sinusitis (acute rhinosinusitis)':'Ear, Nose, Throat, Head and Neck Surgery Department',
'Acute rheumatic fever':'Rheumatology',
'Acute pancreatitis':'Gastroenterology',
'Acute tonsillitis':'Ear, Nose, Throat, Head and Neck Surgery Department',
'Acute viral tonsillopharyngitis':'Ear, Nose, Throat, Head and Neck Surgery Department',
'Acute porphyria':'Endocrinology',
'Acute thyroiditis':'Endocrinology',
"Adrenal insufficiency (Addison's disease)":'Nephrology',
'Adnexitis':'obstetric and gynecology',
'Acute stimulant (amphetamine, cocaine) overdose':'Emergency Medicine',
'Adjustment disorder':'Psychology',
'Alcohol withdrawal syndrome':'Psychology',
'Alcohol poisoning (ethanol toxicity)':'Emergency Medicine',
'Alcoholism':'Psychology',
'Allergic rhinitis':'Ear, Nose, Throat, Head and Neck Surgery Department',
'Allergic conjunctivitis':'Ophthalmology',
"Alzheimer's disease":'Neurology',
'Amebiasis':'Infectious',
'African trypanosomiasis':'Infectious',
'Amyloidosis':'Nephrology',
'Alcoholic liver disease':'Gastroenterology',
'Anal cancer':'General Surgery Division',
'Anal fissure':'General Surgery Division',
"Amyotrophic lateral sclerosis (ALS, Lou Gehrig's disease)":'Neurology',
'Anemia':'Hematology',
'Anorexia':'psychology',
'Ankle osteoarthritis':'Orthopedics',
'Anemia of chronic disease (ACD)':'heamtology',
'Aplastic anemia':'heamtology',
'Agoraphobia':'psychology',
'Ancylostomiasis (hookworm disease, ankylostomiasis, necatoriasis)':'infectious',
'Asthma':'Pulmonary',
'Ankylosing spondylitis (Bamboo spine, Marie-Strumpell disease)':'Immunology',
'Antiphospholipid syndrome (APS, Hughes syndrome)':'Gastroenterology',
'Anxiety disorder with panic attacks':'psychology',
'Appendicitis':'Gastroenterology',
'Asthma':'pulmonary',
'Atopic dermatitis (AD)':'dermatology',
'Atrial fibrillation':'cardiology',
'Autoimmune gastritis':'Gastroenterology',
'Autoimmune hepatitis (AIH)':'immuGastroenterologynology',
'Autoimmune polyendocrine syndrome type 1 (APS-1)':'Gastroenterology',
"Autoimmune' polyendocrine syndrome type 2 (Schmidt's syndrome)":'Gastroenterology',
'Autoimmune polyendocrine syndrome type 3':'Gastroenterology',
'Attention deficit hyperactivity disorder (ADHD)':'psychology',
'Ascariasis':'Gastroenterology',
'Atherogenic hyperlipidemia':'Endocrinology',
'Bacterial meningitis':'neurology',
'Balanoposthitis':'urology',
"Behcet's disease":'immunology',
'Beta-thalassemia':'hematology',
'Bipolar disorder':'neurology',
'Babesiosis':'infectious',
'Bilateral frontal lobe damage':'neurology',
'Bilateral temporal lobe damage':'neurology',
'Biventricular heart failure':'cardiology',
'Bladder cancer':'urology',
'Bleeding peptic ulcer':'Gastroenterology',
'Borreliosis (Lyme disease)':'infectious',
'Breast cancer':'General Surgery Division',
'Botulism':'Emergency Medicine',
'Brain abscess (intracranial abscess, cerebral abscess)':'neurology',
'Brucellosis':'Gastroenterology',
'Budd-Chiari syndrome':'Gastroenterology',
'Bulimia':'psychology',
'Cannabinoid use':'psychology',
'Carbon monoxide poisoning':'Emergency',
'Carcinoid syndrome':'oncology',
'Cardiogenic shock':'Emergency',
'Carotid artery dissection':'emergency',
'Carotid sinus syndrome':'cardiology',
'Carpal tunnel syndrome':'neurology',
'Cat-scratch disease (CSD, cat-scratch fever)':'infectious',
'Cataract':'Ophthalmology',
'Cavernous sinus thrombosis (CST)':'neurology',
'Cerebellar stroke':'emergency',
'Cerebellar tumor (medulloblastoma)':'neurology',
'Cerebral stroke(CVA)':'emergency',
'Cerebral edema':'emergency',
'Celiac disease':'Gastroenterology',
'Cerebellopontine angle syndrome':'neurology',
'Cervicitis':'obstetric and gynecology',
'Chickenpox':'dermatology',
'Cholecystitis':'Gastroenterology',
'Chinese restaurant syndrome':'Gastroenterology',
'Chronic constipation':'Gastroenterology',
'Chalazion':'Ophthalmology',
'Cholera':'Gastroenterology',
'Choriocarcinoma':'obstetric and gynecology',
'Chronic cannabinoid use':'Emergency',
'Chronic eosinophilic leukemia (CEL) and Idiopathic eosinophilia':'heamtology',
'Chronic fatigue syndrome':'general medicine',
'Chronic interstitial nephritis':'nephrology',
'Chronic intestinal ischemia':'Gastroenterology',
'Chronic lower limb ischemia':'Plastic Surgery',
'Chronic lymphocytic leukemia (CLL)':'heamtology',
'Chronic migraine':'neurology',
'Chronic myelogenous leukemia (CML)':'hematology',
'Chronic obstructive jaundice':'Gastroenterology',
'Chronic obstructive pulmonary disease (COPD)':'pulmonary',
'Chronic pancreatitis':'Gastroenterology',
'Chronic renal failure':'nephrology',
'Chronic sinusitis':'Ear, Nose, Throat, Head and Neck Surgery Department',
'Chronic tonsillitis':'Ear, Nose, Throat, Head and Neck Surgery Department',
'Chronic venous insufficiency':'cardiology',
'Churg-Strauss syndrome (eosinophilic granulomatosis with polyangiitis)':'hematology',
'Cirrhosis':'Gastroenterology',
'Cluster headaches (histamine headache)':'neurology',
'Colon cancer (colorectal cancer)':'Gastroenterology',
'Common cold':'general medicine',
'Conjunctivitis':'Ophthalmology',
"Conn's syndrome, primary hyperaldosteronism":'endocrinology',
"Contact dermatitis":'dermatology',
'Corneal abrasion':'Ophthalmology',
'Corneal ulceration':'Ophthalmology',
'Corticotropin releasing pituitary adenoma':'neurology',
"Crohn's disease":'Gastroenterology',
"Cushing's syndrome":'endocrinology',
"Cystitis (bladder infection)":'urology',
"Cysticercosis":'infectious',
"Death cap poisoning":'Emergency',
'Deep vein thrombosis (DVT)':"Emergency",
"Degeneration of the temporomandibular joint":'Dentistry',
"Degenerative disc disease of the cervical spine":'neurology',
'Degenerative disc disease of the lumbar and sacral spine':'neurology',
'Degenerative disc disease of the thoracic spine':'neurology',
"Dehydration":'general medicine',
"Dementia":'neurology',
"Dengue fever":'infectious',
'Dental caries':'Dentistry',
"Dental pulp gangrene":'dentistry',
"Dermatomyositis":'dermatology',
"Diabetes insipidus (DI)":'endocrinology',
"Diabetes mellitus type 1, type 1 diabetes, T1DM":'endocrinology',
"Diabetes mellitus type 2, type 2 diabetes,T2DM":'endocrinology',
"Diabetic polyneuropathy, diabetic neuropathy":"neurology",
"Disulfiram-like reaction (severe alcohol intolerance)":"emergency",
"Diverticulitis":"Gastroenterology",
"Diverticulosis":'Diverticulosis',
"Dubin-Johnson syndrome":'endocrinology',
"Duodenal ulcer":'Gastroenterology',
"Dysmenorrhea":'obstetric and gynecology',
"Ear barotrauma":"Ear, Nose, Throat, Head and Neck Surgery Department",
"Echinococcosis (echinococcal disease)":'infectious',
"Ehrlichiosis":'infectious',
"Empty sella syndrome":'endocrinology',
"Endometrial cancer":'obstetric and gynecology',
"Endometriosis":'obstetric and gynecology',
"Enlarged prostate":'urology',
"Enterobiasis (Pinworms)":'infectious',
"Epilepsy":'neurology',
"Esophageal cancer":'Ear, Nose, Throat, Head and Neck Surgery Department',
"Esophageal diverticula":'Ear, Nose, Throat, Head and Neck Surgery Department',
"Essential thrombocytosis":'hematology',
"Essential tremor":'neurology',
"Extrasystoles (Premature contractions)":'cardiology',
"Eye movement nerve palsy (paralysis of the third, fourth, and sixth cranial nerves)":'Ophthalmology',
"Facial nerve palsy (VIIth cranial nerve)":'neurology',
"Fasciolosis":'infectious',
"Fatigue":'general medicine',
"Felon/whitlow":'dermatology',
"Food poisoning":'Gastroenterology',
"Foot osteoarthritis":"Orthopedics",
"Gall bladder and bile duct cancer":'General Surgery Division',
"Gallstone disease":'General Surgery Division',
"Gastric cancer":'General Surgery Division',
"Gastric ulcer":'Gastroenterology',
"Gastritis":'Gastroenterology',
"Gastritis due to Helicobacter pylori infection":'Gastroenterology',
"Gastritis due to NSAID or corticosteroid use":'Gastroenterology',
"Gastroenteritis":"Gastroenterology",
"Gastroesophageal reflux disease":'Gastroenterology',
"General anxiety disorder":'psychology',
"Genital herpes":'urology',
"Genital warts":'dermatology',
"Gestational diabetes":'obstetric and gynecology',
"Giardiasis (Beaver fever)":'infectious',
"Gilbert's syndrome (Hereditary hyperbilirubinemia)":'endocrinology',
"Gingivitis":"dentistry",
"Gitelman syndrome, familial hypokalemia-hypomagnesemia":'nephrology',
"Glaucoma":'Ophthalmology',
"Glomerulonephritis, glomerular nephritis (GN)":'nephrology',
"Glossitis (inflammation of the tongue)":'dentistry',
"Glossopharyngeal nerve palsy (IXth cranial nerve)":'Ear, Nose, Throat, Head and Neck Surgery Department',
"Gonorrhea":'urology',
"Goodpasture's syndrome":'nephrology',
"Gout":'rheumatology',
"Granulomatosis with polyangiitis (Wegener's granulomatosis)":'dermatology',
"Graves' disease":'endocrinology',
"Guillain-Barre syndrome":'neurology',
"Hand osteoarthritis":'Orthopedics',
"Hashimoto's thyroiditis":'endocrinology',
"Heat illness, Heat-related illness (Heat stroke)":'emergency',
"Hemochromatosis":'Gastroenterology',
"Hemolytic anemia":'hematology',
"Hemolytic-uremic syndrome (HUS)":'nephrology',
"Hemophagocytic lymphohistiocytosis (HLH), hemophagocytic syndrome":'hematology',
"Hemophilia A":'heamtology',
"Hemophilia B (Christmas disease)":'heamtology',
"Hemorrhagic anemia":'emergency',
"Hemorrhoids":'Gastroenterology',
"Henoch-Schonlein purpura":'rheumatology',
'Hepatic abscess':'Gastroenterology',
"Hepatic encephalopathy":'Gastroenterology',
"Hepatic failure or cirrhosis":'Gastroenterology',
"Hepatitis":'Gastroenterology',
"Hepatitis A":'Gastroenterology',
"Hepatitis B":'Gastroenterology',
"Hepatitis C":'Gastroenterology',
"Herbicide poisoning":'emergency',
"Herpes simplex":'dermatology',
"High altitude sickness (acute mountain sickness)":'emergency',
"Hip osteoarthritis":'Orthopedics',
"Hives":'dermatology',
"Hodgkin's lymphoma":'heamtology',
"Horner's syndrome":'neurology',
"Hydrocele testis":'urology',
"Hyperandrogenism":'endocrinology',
"Hyperparathyroidism":'endocrinology',
"Hypertension":'cardiology',
"Hypertensive emergency, malignant hypertension":"cardiology",
"Hypertensive encephalopathy":'Gastroenterology',
"Hyperthyroidism":'endocrinology',
"Hypoglycemia":'emergency',
"Hypoparathyroidism":'endocrinology',
"Hypopituitarism":"endocrinology",
"Hypotension":"cardiology",
"Hypothyroidism":'endocrinology',
"Idiopathic pulmonary fibrosis":'dermatology',
"Impacted wisdom tooth":'dentistry',
"Impetigo":'dermatology',
"Improper use of sleeping pills and sedatives":'psychology',
"Increased intracranial pressure":'energency',
"Infectious arthritis":'Orthopedics',
"Infectious mononucleosis":'infectious',
"Influenza":'Ear, Nose, Throat, Head and Neck Surgery Department',
"Insulinoma":'General Surgery Division',
"Intercostal neuralgia":'',
"Interstitial acute renal failure":'nephrology',
"Intestinal obstruction and paralytic ileus":'gastroentrology',
"Iron deficiency anemia (IDA)":'hematology',
"Irritable bowel syndrome (IBS)":'hematology',
"Ischemic heart disease":"cardiology",
"Kidney cancer":'nephrology',
"Kluver-Bucy bitemporal syndrome":'neurology',
"Knee osteoarthritis":'Orthopedics',
"Korsakoff's syndrome, Korsakoff's dementia, Amnesic-confabulatory syndrome":'neurology',
"Labirynthitis":'Ophthalmology',
"Laryngeal cancer":'Ear, Nose, Throat, Head and Neck Surgery Department',
"Laryngitis":'Ear, Nose, Throat, Head and Neck Surgery Department',
"Lassa fever":'infectious',
"Latent autoimmune diabetes of adults (LADA)":'Rheumatology',
"Lateral medullary syndrome":'neurology',
'Left frontal lobe damage':'neurology',
"Left-sided heart failure":'cardiology',
"Legionellosis":'pulmonary',
"Leriche's syndrome":'cardiology',
"Limbic encephalitis (LE)":'neurology',
"Liver cancer":'Gastroenterology',
"Lung cancer":'pulmonary',
"Major depressive disorder":'psychology',
"Malaria":'infectious',
"Manic syndrome":'psychology',
"Mastocytosis":'Ear, Nose, Throat, Head and Neck Surgery Department',
"Measles":'dermatology',
"Mediastinitis":'pulmonary',
"Melanoma":'dermatology',
"Meningitis":'neurology',
"Menopause":'obstetric and gynecology',
"Methyl alcohol (methanol) poisoning":'emergency',
"Microscopic polyangiitis":'cardiology',
"Middle cerebral artery syndrome, Middle cerebral artery stroke":"neurology",
"Migraine":'neurology',
"Mild Cognitive Impairment (MCI)":'neurology',
"Milk-alkali syndrome":'endocrinology',
"Mixed connective tissue disease":'allergy',
"Molar pregnancy":'obstetric and gynecology',
"Mononeuritis multiplex":'neurology',
"Mucoviscidosis (cystic fibrosis)":'dermatology',
"Multiple endocrine neoplasia type 1 (MEN1), Wermer's syndrome":'endocrinology',
"Multiple endocrine neoplasia type 2A (MEN2A), Sipple's syndrome":'endocrinology',
"Multiple endocrine neoplasia type 2B (MEN2B)":'endocrinology',
"Multiple myeloma":'neurology',
"Multiple sclerosis (MS)":'neurology',
"Mumps (epidemic parotitis)":'neurology',
"Myasthenia gravis":'endocrinology',
"Myelofibrosis, Myeloid metaplasia":'neurology',
"Myocardial infarction, Heart attack":'cardiology',
"Myocarditis":'cardiology',
"Meniere's disease":'Ear, Nose, Throat, Head and Neck Surgery Department',
"Menetrier's disease (giant hypertrophic gastritis)":'Gastroenterology',
"Nasal polyps":'Ear, Nose, Throat, Head and Neck Surgery Department',
"Nephritis":'nephrology',
"Nephrolithiasis":'nephrology',
"Nephrotic syndrome":'nephrology',
"Nicotine dependence":'emergency',
"No ST Elevation Myocardial Infarction":'emergency',
"Non-Hodgkin lymphoma (NHL)":'hematology',
"Nonallergic noninfectious rhinitis":'Ear, Nose, Throat, Head and Neck Surgery Department',
"Obesity":'general medicine',
"Obsessive-compulsive disorder":'psychology',
"Obstructive jaundice":'gastroentrology',
"Oculomotor nerve palsy (IIIrd cranial nerve)":'neurology',
"Orchitis and epididymitis":'urology',
"Osteomalacia":'endocrinology',
"Osteoporosis":'Orthopedics',
"Otitis externa":'Ear, Nose, Throat, Head and Neck Surgery Department',
"Otitis media":'Ear, Nose, Throat, Head and Neck Surgery Department',
"Ovarian cancer":'obstetric and gynecology',
"Paget's disease of bone":'Orthopedics',
"Pancoast tumor":'pulmonary',
"Pancreatic cancer":'gastroentrology',
"Paradontitis":'dentistry',
"Paranoid schizophrenia":'psychology',
"Parkinson's disease":'psychology',
"Paronychia":'infectious',
"Paroxysmal nocturnal hemoglobinuria":'hematology',
"Peptic ulcer":'gastroenterology',
"Pericarditis":'dentistry',
"Peripheral neuropathy":'neurology',
"Peritonitis":'dentistry',
"Peritonsillar abscess (quinsy)":'Ear, Nose, Throat, Head and Neck Surgery Department',
"Pernicious anemia, Biermer's anemia":'hematology',
"Personality disorder":'psychology',
"Pesticide poisoning":'emergency',
"Pheochromocytoma":'endocrinology',
"Pituitary prolactin releasing adenoma (prolactinoma)":'neurology',
"Pituitary somatotropin releasing tumor":'neurology',
"Pituitary tumor":'neurology',
"Placental site trophoblastic tumour":'obstetric and gynecology',
"Plague":'dentistry',
"Plummer-Vinson syndrome, sideropenic dysphagia":'gastroenterology',
"Pneumonia":'pulmonary',
"Pneumothorax":'emergency',
"Polyarteritis nodosa":'rheumatology',
"Polycystic ovary syndrome":'obstetric and gynecology',
"Polycythemia vera (PV, Osler's disease)":'gastroenterology',
"Polymyositis":'Orthopedics',
"Post-traumatic stress disorder":'psychology',
'Postconcussional syndrome':'neurology',
"Postpartum depression":'psychology',
"Pre-eclampsia (gestosis)":'obstetric and gynecology',
"Pregnancy":'obstetric and gynecology',
"Premenstrual syndrome (PMS)":'obstetric and gynecology',
"Prerenal acute renal failure (Prerenal azotemia)":'nephrology',
"Presbycusis":'Ear, Nose, Throat, Head and Neck Surgery Department',
"Primary biliary cirrhosis (PBC)":'gastroenterology',
"Primary sclerosing cholangitis (PSC)":'gastroenterology',
"Prinzmetal's angina":'emergency',
"Progressive supranuclear palsy (PSP)":'neurology',
"Prostate cancer":'urology',
"Prostatitis":'urology',
"Pseudo-Tetany":'endocrinology',
"Pseudobulbar palsy":'neurology',
"Pseudobulbar syndrome with acute vestibulopathy":'neurology',
"Pseudomembranous colitis":'gastroenterology',
"Psittacosis (parrot fever, ornithosis)":'infectious',
"Psoriasis":'dermatology',
"Psychotic depression":'psychology',
"Psychotic mania":'psychology',
"Pulmonary edema":'cardiology',
"Pulmonary embolism":'pulmonary',
"Pulmonary hypertension":'pulmonary',
"Pulpitis":'Ophthalmology',
"Pure hypercholesterolemia":'endocrinology',
"Pure hypertriglyceridemia":'endocrinology',
"Pyelonephritis":'nephrology',
"Q fever":'infectious',
"Ramsay Hunt syndrome type II":'infectios',
"Raynaud's phenomenon":'Emergency',
"Reactive arthritis":'Rheumatology',
"Recurrent laryngeal nerve paralysis":'Ear, Nose, Throat, Head and Neck Surgery Department',
"Reiter's syndrome":'immunology',
"Relapsing fever":'infectious',
"Respiratory failure":'pulmonary',
"Retinal detachment":'Ophthalmology',
"Retinopathy":'Ophthalmology',
"Rheumatoid arthritis":'Rheumatology',
"Rift Valley fever  (RVF)":'infectious',
"Right frontal lobe damage":'neurology',
"Right temporal lobe damage":'neurology',
"Right-sided heart failure":'cardiology',
"Rocky Mountain spotted fever (RMSF)":'infectious',
"Rotor syndrome":'gastroenterology',
"Rubella (German measles)":'infectious',
"ST Elevation Myocardial Infarction":'emergency',
"Salicylate poisoning":'emergency',
"Sarcoidosis":'hematology',
"Scabies":'dermatology',
"Scarlet fever":'infectious',
"Schizoaffective disorder - depressive type":'psychology',
"Schizoaffective disorder - manic type":'psychology',
"Sciatica":'neurology',
"Scoliosis":'Orthopedics',
"Scrub typhus (Bush typhus)":'infectious',
"Scurvy":'general medicine',
"Seasonal affective disorder (winter depression, seasonal depression)":'psychology',
"Seborrheic dermatitis":'dermatology',
"Sexual addiction":'psychology',
"Shigellosis, Bacillary dysentery":'emergency',
"Shingles":'infectious',
"Sickle cell anemia":'hematology',
"Sjogren's syndrome":'endocrinology',
"Skeletal limb trauma":'Orthopedics',
"Sleep apnea":'Ear, Nose, Throat, Head and Neck Surgery Department',
"Sleep apnea, obstructive":'Ear, Nose, Throat, Head and Neck Surgery Department',
"Small intestinal bacterial overgrowth":'Gastroenterology',
"Social anxiety disorder":'psychology',
"Specific phobia":'psychology',
"Spinal osteoarthritis":'orthopedics',
"Stable angina pectoris":'cardiology',
"Stress incontinence":'urology',
"Stye":'Ophthalmology',
"Sudden sensorineural hearing loss (SSNHL, ISSNHL)":'Ear, Nose, Throat, Head and Neck Surgery Department',
"Superficial phlebitis":'cardiology',
"Superior vena cava syndrome (SVCS)":'cardiology',
"Syndrome of inappropriate antidiuretic hormone secretion (SIADH)":'nephrology',
"Systemic lupus erythematosus (SLE)":'rheumatology',
"Systemic scleroderma":'rheumatology',
"Taeniasis":'infectious',
"Takayasu's disease (Takayasu's arteritis)":'rheumatology',
"Temporal giant cell arteritis (GCA)":'rheumatology',
"Tension-type headaches":'neurology',
"Testicular cancer":'urology',
"Testicular torsion":'urology',
"Tetanus":'infectious',
"Tetany":'general medicine',
"Thoracic outlet syndrome (TOS)":'cardiology',
"Thrombocytopathy":'',
"Thrombotic thrombocytopenic purpura (TTP)":'immunology',
"Thymoma":'pulmonary',
"Thyroid cancer":'Ear, Nose, Throat, Head and Neck Surgery Department',
"Thyrotoxicosis":'endocrinology',
"Thyrotropin releasing pituitary adenoma":'neurology',
"Toxocariasis":'infectious',
"Transient ischemic attack (TIA)":'neurology',
"Trichinosis":'infectious',
"Trichomoniasis":'infectious',
"Trichuriasis":'infectious',
"Trigeminal nerve damage (Vth cranial nerve)":'neurology',
"Trigeminal neuralgia":'neurology',
"Trochlear nerve palsy (IVth cranial nerve)":'neurology',
"Trypanosomiasis (Chagas disease, South American trypanosomiasis)":'infectious',
"Tuberculosis":'pulmonary',
"Tuberculous meningitis (TBM)":'neurology',
"Tularemia":'infectious',
"Tumor lysis syndrome":'oncology',
"Type 1 Neurofibromatosis (Von Recklinghausen's Disease)":'oncology',
"Type 2 Neurofibromatosis":'oncology',
"Typhoid, Typhoid fever":'infectious',
"Typhus or Epidemic typhus":'infectious',
"Ulcerative colitis":'gastroenterology',
"Unilateral frontal lobe damage":'neurology',
"Urethritis":'urology',
"Urge incontinence":'urology',
"Urinary tract infection (UTI)":'urology',
"Uterine cancer":'obstetric and gynecology',
"Uterine fibroids":'obstetric and gynecology',
"Uveitis":'Ophthalmology',
"VIPoma, Verner-Morrison syndrome":'oncology',
"Vaginitis":'obstetric and gynecology',
"Vagus nerve palsy (Xth cranial nerve)":'neurology',
"Vascular hemorrhagic diathesis":'hematology',
"Vasculitis":'hematology',
"Vertebrobasilar insufficiency":'neurology',
"Vestibulocochlear nerve damage (VIIIth cranial nerve)":'neurology',
"Viral meningitis":'neurology',
"Visceral leishmaniasis (kala-azar, black fever)":'infectious',
"Vitamin B12 deficiency anemia":'hematology',
"Von Willebrand disease":'hematology',
"Vulvar cancer":'obstetric and gynecology',
"Vulvar cysts":'obstetric and gynecology',
"Waldenstrom's macroglobulinemia":'hematology',
"Warts":'dermatology',
"Water poisoning":'emergency',
"Wernicke's encephalopathy":'neurology',
"Whipple's disease":'gastroenterology',
"Wilson's disease":'neurology',
"Wiskott-Aldrich syndrome":'immunology',
"Withdrawal syndrome (sedatives)":'psychology',
"Yellow fever":'infectious',
"Zollinger-Ellison syndrome, gastrinoma":'oncology',
"de Quervain's thyroiditis (subacute granulomatous thyroiditis, Giant Cell Thyroiditis)":'endocrinology'
}


