clinics = {'Abducens nerve palsy (VIth cranial nerve)': 'neurology',
 'Acetaminophen poisoning': 'emergency medicine',
 'Achalasia': 'gastroenterology',
 'Acne': 'dermatology',
 'Acquired Immunodeficiency syndrome (AIDS)': 'infectious',
 'Acromegaly': 'endocrinology',
 'Acute HIV infection (acute retroviral syndrome, early symptomatic HIV Infection)': 'infectious',
 'Acute anticholinergic syndrome': 'emergency medicine',
 'Acute bronchitis': 'pulmonary',
 'Acute cholinergic syndrome': 'emergency medicine',
 'Acute hypnotic toxicity': 'emergency medicine',
 'Acute interstitial nephritis': 'nephrology',
 'Acute intestinal ischemia': 'general surgery division',
 'Acute liver failure': 'gastroenterology',
 'Acute lymphoblastic leukemia (ALL)': 'oncology',
 'Acute mastoiditis': 'ear, nose, throat, head and neck surgery department',
 'Acute myeloid leukemia (AML)': 'oncology',
 'Acute pancreatitis': 'gastroenterology',
 'Acute pharyngitis': 'ear, nose, throat, head and neck surgery department',
 'Acute porphyria': 'endocrinology',
 'Acute rheumatic fever': 'rheumatology',
 'Acute sinusitis (acute rhinosinusitis)': 'ear, nose, throat, head and neck surgery department',
 'Acute stimulant (amphetamine, cocaine) overdose': 'emergency medicine',
 'Acute thyroiditis': 'endocrinology',
 'Acute tonsillitis': 'ear, nose, throat, head and neck surgery department',
 'Acute viral tonsillopharyngitis': 'ear, nose, throat, head and neck surgery department',
 'Adjustment disorder': 'psychology',
 'Adnexitis': 'obstetric and gynecology',
 "Adrenal insufficiency (Addison's disease)": 'nephrology',
 'African trypanosomiasis': 'infectious',
 'Agoraphobia': 'psychology',
 'Alcohol poisoning (ethanol toxicity)': 'emergency medicine',
 'Alcohol withdrawal syndrome': 'psychology',
 'Alcoholic liver disease': 'gastroenterology',
 'Alcoholism': 'psychology',
 'Allergic conjunctivitis': 'ophthalmology',
 'Allergic rhinitis': 'ear, nose, throat, head and neck surgery department',
 "Alzheimer's disease": 'neurology',
 'Amebiasis': 'infectious',
 'Amyloidosis': 'nephrology',
 "Amyotrophic lateral sclerosis (ALS, Lou Gehrig's disease)": 'neurology',
 'Anal cancer': 'general surgery division',
 'Anal fissure': 'general surgery division',
 'Ancylostomiasis (hookworm disease, ankylostomiasis, necatoriasis)': 'infectious',
 'Anemia': 'hematology',
 'Anemia of chronic disease (ACD)': 'hematology',
 'Ankle osteoarthritis': 'orthopedics',
 'Ankylosing spondylitis (Bamboo spine, Marie-Strumpell disease)': 'immunology',
 'Anorexia': 'psychology',
 'Antiphospholipid syndrome (APS, Hughes syndrome)': 'gastroenterology',
 'Anxiety disorder with panic attacks': 'psychology',
 'Aplastic anemia': 'hematology',
 'Appendicitis': 'gastroenterology',
 'Ascariasis': 'gastroenterology',
 'Asthma': 'pulmonary',
 'Atherogenic hyperlipidemia': 'endocrinology',
 'Atopic dermatitis (AD)': 'dermatology',
 'Atrial fibrillation': 'cardiology',
 'Attention deficit hyperactivity disorder (ADHD)': 'psychology',
 'Autoimmune gastritis': 'gastroenterology',
 'Autoimmune hepatitis (AIH)': 'gastroenterology',
 'Autoimmune polyendocrine syndrome type 1 (APS-1)': 'gastroenterology',
 'Autoimmune polyendocrine syndrome type 3': 'gastroenterology',
 "Autoimmune' polyendocrine syndrome type 2 (Schmidt's syndrome)": 'gastroenterology',
 'Babesiosis': 'infectious',
 'Bacterial meningitis': 'neurology',
 'Balanoposthitis': 'urology',
 "Behcet's disease": 'immunology',
 'Beta-thalassemia': 'hematology',
 'Bilateral frontal lobe damage': 'neurology',
 'Bilateral temporal lobe damage': 'neurology',
 'Bipolar disorder': 'neurology',
 'Biventricular heart failure': 'cardiology',
 'Bladder cancer': 'urology',
 'Bleeding peptic ulcer': 'gastroenterology',
 'Borreliosis (Lyme disease)': 'infectious',
 'Botulism': 'emergency medicine',
 'Brain abscess (intracranial abscess, cerebral abscess)': 'neurology',
 'Breast cancer': 'general surgery division',
 'Brucellosis': 'gastroenterology',
 'Budd-Chiari syndrome': 'gastroenterology',
 'Bulimia': 'psychology',
 'Cannabinoid use': 'psychology',
 'Carbon monoxide poisoning': 'emergency',
 'Carcinoid syndrome': 'oncology',
 'Cardiogenic shock': 'emergency',
 'Carotid artery dissection': 'emergency',
 'Carotid sinus syndrome': 'cardiology',
 'Carpal tunnel syndrome': 'neurology',
 'Cat-scratch disease (CSD, cat-scratch fever)': 'infectious',
 'Cataract': 'ophthalmology',
 'Cavernous sinus thrombosis (CST)': 'neurology',
 'Celiac disease': 'gastroenterology',
 'Cerebellar stroke': 'emergency',
 'Cerebellar tumor (medulloblastoma)': 'neurology',
 'Cerebellopontine angle syndrome': 'neurology',
 'Cerebral edema': 'emergency',
 'Cerebral stroke(CVA)': 'emergency',
 'Cervicitis': 'obstetric and gynecology',
 'Chalazion': 'ophthalmology',
 'Chickenpox': 'dermatology',
 'Chinese restaurant syndrome': 'gastroenterology',
 'Cholecystitis': 'gastroenterology',
 'Cholera': 'gastroenterology',
 'Choriocarcinoma': 'obstetric and gynecology',
 'Chronic cannabinoid use': 'emergency',
 'Chronic constipation': 'gastroenterology',
 'Chronic eosinophilic leukemia (CEL) and Idiopathic eosinophilia': 'hematology',
 'Chronic fatigue syndrome': 'general medicine',
 'Chronic interstitial nephritis': 'nephrology',
 'Chronic intestinal ischemia': 'gastroenterology',
 'Chronic lower limb ischemia': 'plastic surgery',
 'Chronic lymphocytic leukemia (CLL)': 'hematology',
 'Chronic migraine': 'neurology',
 'Chronic myelogenous leukemia (CML)': 'hematology',
 'Chronic obstructive jaundice': 'gastroenterology',
 'Chronic obstructive pulmonarydisease (COPD)': 'pulmonary',
 'Chronic pancreatitis': 'gastroenterology',
 'Chronic renal failure': 'nephrology',
 'Chronic sinusitis': 'ear, nose, throat, head and neck surgery department',
 'Chronic tonsillitis': 'ear, nose, throat, head and neck surgery department',
 'Chronic venous insufficiency': 'cardiology',
 'Churg-Strauss syndrome (eosinophilic granulomatosis with polyangiitis)': 'hematology',
 'Cirrhosis': 'gastroenterology',
 'Cluster headaches (histamine headache)': 'neurology',
 'Colon cancer (colorectal cancer)': 'gastroenterology',
 'Common cold': 'general medicine',
 'Conjunctivitis': 'ophthalmology',
 "Conn's syndrome, primary hyperaldosteronism": 'endocrinology',
 'Contact dermatitis': 'dermatology',
 'Corneal abrasion': 'ophthalmology',
 'Corneal ulceration': 'ophthalmology',
 'Corticotropin releasing pituitary adenoma': 'neurology',
 "Crohn's disease": 'gastroenterology',
 "Cushing's syndrome": 'endocrinology',
 'Cysticercosis': 'infectious',
 'Cystitis (bladder infection)': 'urology',
 'Death cap poisoning': 'emergency',
 'Deep vein thrombosis (DVT)': 'emergency',
 'Degeneration of the temporomandibular joint': 'dentistry',
 'Degenerative disc disease of the cervical spine': 'neurology',
 'Degenerative disc disease of the lumbar and sacral spine': 'neurology',
 'Degenerative disc disease of the thoracic spine': 'neurology',
 'Dehydration': 'general medicine',
 'Dementia': 'neurology',
 'Dengue fever': 'infectious',
 'Dental caries': 'dentistry',
 'Dental pulp gangrene': 'dentistry',
 'Dermatomyositis': 'dermatology',
 'Diabetes insipidus (DI)': 'endocrinology',
 'Diabetes mellitus type 1, type 1 diabetes, T1DM': 'endocrinology',
 'Diabetes mellitus type 2, type 2 diabetes,T2DM': 'endocrinology',
 'Diabetic polyneuropathy, diabetic neuropathy': 'neurology',
 'Disulfiram-like reaction (severe alcohol intolerance)': 'emergency',
 'Diverticulitis': 'gastroenterology',
 'Diverticulosis': 'diverticulosis',
 'Dubin-Johnson syndrome': 'endocrinology',
 'Duodenal ulcer': 'gastroenterology',
 'Dysmenorrhea': 'obstetric and gynecology',
 'Ear barotrauma': 'ear, nose, throat, head and neck surgery department',
 'Echinococcosis (echinococcal disease)': 'infectious',
 'Ehrlichiosis': 'infectious',
 'Empty sella syndrome': 'endocrinology',
 'Endometrial cancer': 'obstetric and gynecology',
 'Endometriosis': 'obstetric and gynecology',
 'Enlarged prostate': 'urology',
 'Enterobiasis (Pinworms)': 'infectious',
 'Epilepsy': 'neurology',
 'Esophageal cancer': 'ear, nose, throat, head and neck surgery department',
 'Esophageal diverticula': 'ear, nose, throat, head and neck surgery department',
 'Essential thrombocytosis': 'hematology',
 'Essential tremor': 'neurology',
 'Extrasystoles (Premature contractions)': 'cardiology',
 'Eye movement nerve palsy (paralysis of the third, fourth, and sixth cranial nerves)': 'ophthalmology',
 'Facial nerve palsy (VIIth cranial nerve)': 'neurology',
 'Fasciolosis': 'infectious',
 'Fatigue': 'general medicine',
 'Felon/whitlow': 'dermatology',
 'Food poisoning': 'gastroenterology',
 'Foot osteoarthritis': 'orthopedics',
 'Gall bladder and bile duct cancer': 'general surgery division',
 'Gallstone disease': 'general surgery division',
 'Gastric cancer': 'general surgery division',
 'Gastric ulcer': 'gastroenterology',
 'Gastritis': 'gastroenterology',
 'Gastritis due to Helicobacter pylori infection': 'gastroenterology',
 'Gastritis due to NSAID or corticosteroid use': 'gastroenterology',
 'Gastroenteritis': 'gastroenterology',
 'Gastroesophageal reflux disease': 'gastroenterology',
 'General anxiety disorder': 'psychology',
 'Genital herpes': 'urology',
 'Genital warts': 'dermatology',
 'Gestational diabetes': 'obstetric and gynecology',
 'Giardiasis (Beaver fever)': 'infectious',
 "Gilbert's syndrome (Hereditary hyperbilirubinemia)": 'endocrinology',
 'Gingivitis': 'dentistry',
 'Gitelman syndrome, familial hypokalemia-hypomagnesemia': 'nephrology',
 'Glaucoma': 'ophthalmology',
 'Glomerulonephritis, glomerular nephritis (GN)': 'nephrology',
 'Glossitis (inflammation of the tongue)': 'dentistry',
 'Glossopharyngeal nerve palsy (IXth cranial nerve)': 'ear, nose, throat, head and neck surgery department',
 'Gonorrhea': 'urology',
 "Goodpasture's syndrome": 'nephrology',
 'Gout': 'rheumatology',
 "Granulomatosis with polyangiitis (Wegener's granulomatosis)": 'dermatology',
 "Graves' disease": 'endocrinology',
 'Guillain-Barre syndrome': 'neurology',
 'Hand osteoarthritis': 'orthopedics',
 "Hashimoto's thyroiditis": 'endocrinology',
 'Heat illness, Heat-related illness (Heat stroke)': 'emergency',
 'Hemochromatosis': 'gastroenterology',
 'Hemolytic anemia': 'hematology',
 'Hemolytic-uremic syndrome (HUS)': 'nephrology',
 'Hemophagocytic lymphohistiocytosis (HLH), hemophagocytic syndrome': 'hematology',
 'Hemophilia A': 'hematology',
 'Hemophilia B (Christmas disease)': 'hematology',
 'Hemorrhagic anemia': 'emergency',
 'Hemorrhoids': 'gastroenterology',
 'Henoch-Schonlein purpura': 'rheumatology',
 'Hepatic abscess': 'gastroenterology',
 'Hepatic encephalopathy': 'gastroenterology',
 'Hepatic failure or cirrhosis': 'gastroenterology',
 'Hepatitis': 'gastroenterology',
 'Hepatitis A': 'gastroenterology',
 'Hepatitis B': 'gastroenterology',
 'Hepatitis C': 'gastroenterology',
 'Herbicide poisoning': 'emergency',
 'Herpes simplex': 'dermatology',
 'High altitude sickness (acute mountain sickness)': 'emergency',
 'Hip osteoarthritis': 'orthopedics',
 'Hives': 'dermatology',
 "Hodgkin's lymphoma": 'hematology',
 "Horner's syndrome": 'neurology',
 'Hydrocele testis': 'urology',
 'Hyperandrogenism': 'endocrinology',
 'Hyperparathyroidism': 'endocrinology',
 'Hypertension': 'cardiology',
 'Hypertensive emergency, malignant hypertension': 'cardiology',
 'Hypertensive encephalopathy': 'gastroenterology',
 'Hyperthyroidism': 'endocrinology',
 'Hypoglycemia': 'emergency',
 'Hypoparathyroidism': 'endocrinology',
 'Hypopituitarism': 'endocrinology',
 'Hypotension': 'cardiology',
 'Hypothyroidism': 'endocrinology',
 'Idiopathic pulmonaryfibrosis': 'dermatology',
 'Impacted wisdom tooth': 'dentistry',
 'Impetigo': 'dermatology',
 'Improper use of sleeping pills and sedatives': 'psychology',
 'Increased intracranial pressure': 'emergency',
 'Infectious arthritis': 'orthopedics',
 'Infectious mononucleosis': 'infectious',
 'Influenza': 'ear, nose, throat, head and neck surgery department',
 'Insulinoma': 'general surgery division',
 'Intercostal neuralgia': '',
 'Interstitial acute renal failure': 'nephrology',
 'Intestinal obstruction and paralytic ileus': 'gastroenterology',
 'Iron deficiency anemia (IDA)': 'hematology',
 'Irritable bowel syndrome (IBS)': 'hematology',
 'Ischemic heart disease': 'cardiology',
 'Kidney cancer': 'nephrology',
 'Kluver-Bucy bitemporal syndrome': 'neurology',
 'Knee osteoarthritis': 'orthopedics',
 "Korsakoff's syndrome, Korsakoff's dementia, Amnesic-confabulatory syndrome": 'neurology',
 'Labirynthitis': 'ophthalmology',
 'Laryngeal cancer': 'ear, nose, throat, head and neck surgery department',
 'Laryngitis': 'ear, nose, throat, head and neck surgery department',
 'Lassa fever': 'infectious',
 'Latent autoimmune diabetes of adults (LADA)': 'rheumatology',
 'Lateral medullary syndrome': 'neurology',
 'Left frontal lobe damage': 'neurology',
 'Left-sided heart failure': 'cardiology',
 'Legionellosis': 'pulmonary',
 "Leriche's syndrome": 'cardiology',
 'Limbic encephalitis (LE)': 'neurology',
 'Liver cancer': 'gastroenterology',
 'Lung cancer': 'pulmonary',
 'Major depressive disorder': 'psychology',
 'Malaria': 'infectious',
 'Manic syndrome': 'psychology',
 'Mastocytosis': 'ear, nose, throat, head and neck surgery department',
 'Measles': 'dermatology',
 'Mediastinitis': 'pulmonary',
 'Melanoma': 'dermatology',
 "Menetrier's disease (giant hypertrophic gastritis)": 'gastroenterology',
 "Meniere's disease": 'ear, nose, throat, head and neck surgery department',
 'Meningitis': 'neurology',
 'Menopause': 'obstetric and gynecology',
 'Methyl alcohol (methanol) poisoning': 'emergency',
 'Microscopic polyangiitis': 'cardiology',
 'Middle cerebral artery syndrome, Middle cerebral artery stroke': 'neurology',
 'Migraine': 'neurology',
 'Mild Cognitive Impairment (MCI)': 'neurology',
 'Milk-alkali syndrome': 'endocrinology',
 'Mixed connective tissue disease': 'allergy',
 'Molar pregnancy': 'obstetric and gynecology',
 'Mononeuritis multiplex': 'neurology',
 'Mucoviscidosis (cystic fibrosis)': 'dermatology',
 "Multiple endocrine neoplasia type 1 (MEN1), Wermer's syndrome": 'endocrinology',
 "Multiple endocrine neoplasia type 2A (MEN2A), Sipple's syndrome": 'endocrinology',
 'Multiple endocrine neoplasia type 2B (MEN2B)': 'endocrinology',
 'Multiple myeloma': 'neurology',
 'Multiple sclerosis (MS)': 'neurology',
 'Mumps (epidemic parotitis)': 'neurology',
 'Myasthenia gravis': 'endocrinology',
 'Myelofibrosis, Myeloid metaplasia': 'neurology',
 'Myocardial infarction, Heart attack': 'cardiology',
 'Myocarditis': 'cardiology',
 'Nasal polyps': 'ear, nose, throat, head and neck surgery department',
 'Nephritis': 'nephrology',
 'Nephrolithiasis': 'nephrology',
 'Nephrotic syndrome': 'nephrology',
 'Nicotine dependence': 'emergency',
 'No ST Elevation Myocardial Infarction': 'emergency',
 'Non-Hodgkin lymphoma (NHL)': 'hematology',
 'Nonallergic noninfectious rhinitis': 'ear, nose, throat, head and neck surgery department',
 'Obesity': 'general medicine',
 'Obsessive-compulsive disorder': 'psychology',
 'Obstructive jaundice': 'gastroenterology',
 'Oculomotor nerve palsy (IIIrd cranial nerve)': 'neurology',
 'Orchitis and epididymitis': 'urology',
 'Osteomalacia': 'endocrinology',
 'Osteoporosis': 'orthopedics',
 'Otitis externa': 'ear, nose, throat, head and neck surgery department',
 'Otitis media': 'ear, nose, throat, head and neck surgery department',
 'Ovarian cancer': 'obstetric and gynecology',
 "Paget's disease of bone": 'orthopedics',
 'Pancoast tumor': 'pulmonary',
 'Pancreatic cancer': 'gastroenterology',
 'Paradontitis': 'dentistry',
 'Paranoid schizophrenia': 'psychology',
 "Parkinson's disease": 'psychology',
 'Paronychia': 'infectious',
 'Paroxysmal nocturnal hemoglobinuria': 'hematology',
 'Peptic ulcer': 'gastroenterology',
 'Pericarditis': 'cardiology',
 'Peripheral neuropathy': 'neurology',
 'Peritonitis': 'dentistry',
 'Peritonsillar abscess (quinsy)': 'ear, nose, throat, head and neck surgery department',
 "Pernicious anemia, Biermer's anemia": 'hematology',
 'Personality disorder': 'psychology',
 'Pesticide poisoning': 'emergency',
 'Pheochromocytoma': 'endocrinology',
 'Pituitary prolactin releasing adenoma (prolactinoma)': 'neurology',
 'Pituitary somatotropin releasing tumor': 'neurology',
 'Pituitary tumor': 'neurology',
 'Placental site trophoblastic tumour': 'obstetric and gynecology',
 'Plague': 'dentistry',
 'Plummer-Vinson syndrome, sideropenic dysphagia': 'gastroenterology',
 'Pneumonia': 'pulmonary',
 'Pneumothorax': 'emergency',
 'Polyarteritis nodosa': 'rheumatology',
 'Polycystic ovary syndrome': 'obstetric and gynecology',
 "Polycythemia vera (PV, Osler's disease)": 'gastroenterology',
 'Polymyositis': 'orthopedics',
 'Post-traumatic stress disorder': 'psychology',
 'Postconcussional syndrome': 'neurology',
 'Postpartum depression': 'psychology',
 'Pre-eclampsia (gestosis)': 'obstetric and gynecology',
 'Pregnancy': 'obstetric and gynecology',
 'Premenstrual syndrome (PMS)': 'obstetric and gynecology',
 'Prerenal acute renal failure (Prerenal azotemia)': 'nephrology',
 'Presbycusis': 'ear, nose, throat, head and neck surgery department',
 'Primary biliary cirrhosis (PBC)': 'gastroenterology',
 'Primary sclerosing cholangitis (PSC)': 'gastroenterology',
 "Prinzmetal's angina": 'emergency',
 'Progressive supranuclear palsy (PSP)': 'neurology',
 'Prostate cancer': 'urology',
 'Prostatitis': 'urology',
 'Pseudo-Tetany': 'endocrinology',
 'Pseudobulbar palsy': 'neurology',
 'Pseudobulbar syndrome with acute vestibulopathy': 'neurology',
 'Pseudomembranous colitis': 'gastroenterology',
 'Psittacosis (parrot fever, ornithosis)': 'infectious',
 'Psoriasis': 'dermatology',
 'Psychotic depression': 'psychology',
 'Psychotic mania': 'psychology',
 'Pulmonary edema': 'cardiology',
 'Pulmonary embolism': 'pulmonary',
 'Pulmonary hypertension': 'pulmonary',
 'Pulpitis': 'ophthalmology',
 'Pure hypercholesterolemia': 'endocrinology',
 'Pure hypertriglyceridemia': 'endocrinology',
 'Pyelonephritis': 'nephrology',
 'Q fever': 'infectious',
 'Ramsay Hunt syndrome type II': 'infectious',
 "Raynaud's phenomenon": 'emergency',
 'Reactive arthritis': 'rheumatology',
 'Recurrent laryngeal nerve paralysis': 'ear, nose, throat, head and neck surgery department',
 "Reiter's syndrome": 'immunology',
 'Relapsing fever': 'infectious',
 'Respiratory failure': 'pulmonary',
 'Retinal detachment': 'ophthalmology',
 'Retinopathy': 'ophthalmology',
 'Rheumatoid arthritis': 'rheumatology',
 'Rift Valley fever  (RVF)': 'infectious',
 'Right frontal lobe damage': 'neurology',
 'Right temporal lobe damage': 'neurology',
 'Right-sided heart failure': 'cardiology',
 'Rocky Mountain spotted fever (RMSF)': 'infectious',
 'Rotor syndrome': 'gastroenterology',
 'Rubella (German measles)': 'infectious',
 'ST Elevation Myocardial Infarction': 'emergency',
 'Salicylate poisoning': 'emergency',
 'Sarcoidosis': 'hematology',
 'Scabies': 'dermatology',
 'Scarlet fever': 'infectious',
 'Schizoaffective disorder - depressive type': 'psychology',
 'Schizoaffective disorder - manic type': 'psychology',
 'Sciatica': 'neurology',
 'Scoliosis': 'orthopedics',
 'Scrub typhus (Bush typhus)': 'infectious',
 'Scurvy': 'general medicine',
 'Seasonal affective disorder (winter depression, seasonal depression)': 'psychology',
 'Seborrheic dermatitis': 'dermatology',
 'Sexual addiction': 'psychology',
 'Shigellosis, Bacillary dysentery': 'emergency',
 'Shingles': 'infectious',
 'Sickle cell anemia': 'hematology',
 "Sjogren's syndrome": 'endocrinology',
 'Skeletal limb trauma': 'orthopedics',
 'Sleep apnea': 'ear, nose, throat, head and neck surgery department',
 'Sleep apnea, obstructive': 'ear, nose, throat, head and neck surgery department',
 'Small intestinal bacterial overgrowth': 'gastroenterology',
 'Social anxiety disorder': 'psychology',
 'Specific phobia': 'psychology',
 'Spinal osteoarthritis': 'orthopedics',
 'Stable angina pectoris': 'cardiology',
 'Stress incontinence': 'urology',
 'Stye': 'ophthalmology',
 'Sudden sensorineural hearing loss (SSNHL, ISSNHL)': 'ear, nose, throat, head and neck surgery department',
 'Superficial phlebitis': 'cardiology',
 'Superior vena cava syndrome (SVCS)': 'cardiology',
 'Syndrome of inappropriate antidiuretic hormone secretion (SIADH)': 'nephrology',
 'Systemic lupus erythematosus (SLE)': 'rheumatology',
 'Systemic scleroderma': 'rheumatology',
 'Taeniasis': 'infectious',
 "Takayasu's disease (Takayasu's arteritis)": 'rheumatology',
 'Temporal giant cell arteritis (GCA)': 'rheumatology',
 'Tension-type headaches': 'neurology',
 'Testicular cancer': 'urology',
 'Testicular torsion': 'urology',
 'Tetanus': 'infectious',
 'Tetany': 'general medicine',
 'Thoracic outlet syndrome (TOS)': 'cardiology',
 'Thrombocytopathy': '',
 'Thrombotic thrombocytopenic purpura (TTP)': 'immunology',
 'Thymoma': 'pulmonary',
 'Thyroid cancer': 'ear, nose, throat, head and neck surgery department',
 'Thyrotoxicosis': 'endocrinology',
 'Thyrotropin releasing pituitary adenoma': 'neurology',
 'Toxocariasis': 'infectious',
 'Transient ischemic attack (TIA)': 'neurology',
 'Trichinosis': 'infectious',
 'Trichomoniasis': 'infectious',
 'Trichuriasis': 'infectious',
 'Trigeminal nerve damage (Vth cranial nerve)': 'neurology',
 'Trigeminal neuralgia': 'neurology',
 'Trochlear nerve palsy (IVth cranial nerve)': 'neurology',
 'Trypanosomiasis (Chagas disease, South American trypanosomiasis)': 'infectious',
 'Tuberculosis': 'pulmonary',
 'Tuberculous meningitis (TBM)': 'neurology',
 'Tularemia': 'infectious',
 'Tumor lysis syndrome': 'oncology',
 "Type 1 Neurofibromatosis (Von Recklinghausen's Disease)": 'oncology',
 'Type 2 Neurofibromatosis': 'oncology',
 'Typhoid, Typhoid fever': 'infectious',
 'Typhus or Epidemic typhus': 'infectious',
 'Ulcerative colitis': 'gastroenterology',
 'Unilateral frontal lobe damage': 'neurology',
 'Urethritis': 'urology',
 'Urge incontinence': 'urology',
 'Urinary tract infection (UTI)': 'urology',
 'Uterine cancer': 'obstetric and gynecology',
 'Uterine fibroids': 'obstetric and gynecology',
 'Uveitis': 'ophthalmology',
 'VIPoma, Verner-Morrison syndrome': 'oncology',
 'Vaginitis': 'obstetric and gynecology',
 'Vagus nerve palsy (Xth cranial nerve)': 'neurology',
 'Vascular hemorrhagic diathesis': 'hematology',
 'Vasculitis': 'hematology',
 'Vertebrobasilar insufficiency': 'neurology',
 'Vestibulocochlear nerve damage (VIIIth cranial nerve)': 'neurology',
 'Viral meningitis': 'neurology',
 'Visceral leishmaniasis (kala-azar, black fever)': 'infectious',
 'Vitamin B12 deficiency anemia': 'hematology',
 'Von Willebrand disease': 'hematology',
 'Vulvar cancer': 'obstetric and gynecology',
 'Vulvar cysts': 'obstetric and gynecology',
 "Waldenstrom's macroglobulinemia": 'hematology',
 'Warts': 'dermatology',
 'Water poisoning': 'emergency',
 "Wernicke's encephalopathy": 'neurology',
 "Whipple's disease": 'gastroenterology',
 "Wilson's disease": 'neurology',
 'Wiskott-Aldrich syndrome': 'immunology',
 'Withdrawal syndrome (sedatives)': 'psychology',
 'Yellow fever': 'infectious',
 'Zollinger-Ellison syndrome, gastrinoma': 'oncology',
 "de Quervain's thyroiditis (subacute granulomatous thyroiditis, Giant Cell Thyroiditis)": 'endocrinology'}
